FROM ros:noetic-ros-base-focal

# from https://varhowto.com/install-ros-noetic-docker/
#FROM ros:noetic-robot

# Arguments
ARG user
ARG uid
ARG home
ARG workspace
ARG shell
ARG nvidia_driver_version
ARG container_name
ARG timezone=Etc/UTC

LABEL maintainer="luigifreda@gmail.com"

ENV TZ=${timezone}

################################

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y keyboard-configuration

# Basic Utilities
RUN apt-get -y update && apt-get install -y screen tree sudo ssh synaptic psmisc aptitude gedit geany 
RUN apt-get install -y git curl wget ca-certificates 

# Latest X11 / mesa GL
RUN apt-get install -y mesa-utils 

# Dependencies required to build rviz (already installed in ros:noetic-robot: from https://varhowto.com/install-ros-noetic-docker/)
RUN apt-get install -y libqt5core5a libqt5dbus5 libqt5gui5 

# Additional development tools
RUN apt-get install -y build-essential git

# ROS-desktop
RUN apt-get install -y ros-noetic-desktop-full
RUN rm /etc/ros/rosdep/sources.list.d/20-default.list
RUN rosdep init && rosdep update

# Python 
RUN apt-get install -y python3-pip
RUN apt-get install -y python-is-python3
RUN pip3 install -U catkin_tools

# ROS deps
RUN apt-get install -y \
#python-rosinstall \
#python-jinja2 \
doxygen \
libssh2-1-dev \
libudev-dev 

RUN apt-get update && apt-get install -y locales \
 && sed -i 's/^# *en_US\.UTF-8/en_US.UTF-8/' /etc/locale.gen \
 && locale-gen \
 && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV XDG_RUNTIME_DIR=/tmp/runtime-root
RUN mkdir -p /tmp/runtime-root && chmod 700 /tmp/runtime-root

################################

# from  http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration  (with nvidia-docker2)
# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

# Make SSH available
EXPOSE 22

# Mount the user's home directory
VOLUME "${home}"

RUN useradd ${user} -m -s ${shell} -u ${uid} -G sudo,dialout

# Clone user into docker image and set up X11 sharing 
RUN \
  echo "${user}:x:${uid}:${uid}:${user},,,:${home}:${shell}" >> /etc/passwd && \
  echo "${user}:x:${uid}:" >> /etc/group && \
  echo "${user} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${user}" && \
  chmod 0440 "/etc/sudoers.d/${user}"

#RUN echo "${user} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers 
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN echo "${user}:docker" | chpasswd 
# this allows to switch to user with $ su -
RUN echo "root:docker" | chpasswd  

# Switch to user
USER "${user}"

# This is required for sharing Xauthority
ENV QT_X11_NO_MITSHM=1

ENV CONTAINER_NAME="${container_name}"

# Switch to the workspace
WORKDIR ${workspace}

COPY ./bashrc_add ${home}/bashrc_add
RUN cat ${home}/bashrc_add >> "${home}/.bashrc"
