# first build a local noetic as detailed in the README 
FROM noetic   

# from https://varhowto.com/install-ros-noetic-docker/
#FROM ros:noetic-robot

# Arguments
ARG user
ARG uid
ARG home
ARG workspace
ARG shell
ARG nvidia_driver_version
ARG container_name

LABEL maintainer="luigifreda@gmail.com"

################################

# switch to root 
USER root  

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y keyboard-configuration
RUN apt-get install -y git curl wget ca-certificates 

# Switch to user
USER "${user}"

# Install and configure git
RUN sudo mkdir -p /home/${user}/.ssh && sudo chmod 0777 -R /home/${user}
RUN touch ~/.gitconfig && touch ~/.ssh/known_hosts
#RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
RUN git config --global user.name "${user}"
RUN git config --global user.email "${user}@${user}.com"

# Install 3dmr
WORKDIR /tmp
RUN git clone https://github.com/luigifreda/3dmr.git 
# the following to inform we are inside docker at build time 
RUN sudo touch /.dockerenv 
RUN cd 3dmr && ./install.sh 
RUN rm -Rf 3dmr 

WORKDIR ${home}