# first build a local noetic as detailed in the README 
FROM noetic   

# from https://varhowto.com/install-ros-noetic-docker/
#FROM ros:noetic-robot

# Arguments
ARG user
ARG uid
ARG home
ARG workspace
ARG shell
ARG nvidia_driver_version
ARG container_name
ARG timezone=Etc/UTC

LABEL maintainer="luigifreda@gmail.com"

ENV TZ=${timezone}

################################

# switch to root 
USER root  

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y keyboard-configuration
RUN apt-get install -y git curl wget ca-certificates 

# Set locale
RUN apt-get update && apt-get install -y locales \
 && sed -i 's/^# *en_US\.UTF-8/en_US.UTF-8/' /etc/locale.gen \
 && locale-gen \
 && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV XDG_RUNTIME_DIR=/tmp/runtime-root
RUN mkdir -p /tmp/runtime-root && chmod 700 /tmp/runtime-root


# Switch to user
USER "${user}"

RUN sudo chown -R ${user}:${user} ${home} && sudo chmod -R u+rwx ${home}

# Install and configure git
RUN sudo mkdir -p /home/${user}/.ssh && sudo chmod 0777 -R /home/${user}
#RUN touch ~/.gitconfig && touch ~/.ssh/known_hosts
RUN sudo touch ${home}/.gitconfig && sudo chown ${user}:${user} ${home}/.gitconfig && sudo chmod 644 ${home}/.gitconfig
RUN sudo touch ${home}/.ssh/known_hosts && sudo chown ${user}:${user} ${home}/.ssh/known_hosts && sudo chmod 644 ${home}/.ssh/known_hosts
#RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
RUN git config --global user.name "${user}"
RUN git config --global user.email "${user}@${user}.com"
RUN git config --global http.proxy ""
RUN sudo git config --system --add safe.directory '*' # to avoid "detected dubious ownership" error

# Install 3dmr
WORKDIR /tmp
RUN git clone https://github.com/luigifreda/3dmr.git 
# the following to inform we are inside docker at build time 
RUN sudo touch /.dockerenv 
RUN cd 3dmr && ./install.sh 
RUN rm -Rf 3dmr 

WORKDIR ${home}